repositories {
    maven { url = 'https://api.modrinth.com/maven' }
}

architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    modCompileOnly "maven.modrinth:pehkui:3.8.2+1.14.4-1.20.6"
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"

    modImplementation files(rootProject.lenloruiArtifact(
            "${rootProject.lenlorui_project}/common/build/devlibs/LenlorUI-common-${rootProject.lenlorui_version}-dev.jar"))
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
